### ISSUE TITLE
Mod connects clients to whatever ngrok api returns first

### ISSUE THREAD

**Issue by fpp3** [jaanonim/ngrok-api#5]
I have my minecraft server with 2 open ngrok tunnels (server and ssh). The mod always shows one of them on the server list. Sometimes its the minecraft server tunnel, and sometimes its the other tunnel. This makes the players unable to join the server because its trying to connect to the wrong tunnel. I think that adding a way to filter out different tunnels from the actual minecraft server (maybe by implementing a way of knowing what tunnel is a minecraft server is a minecraft server and whats not, or by simply figuring out what tunnel gets to local port 25565) should be added.

I'm running minecraft 1.18.2, using mod version 1.0.2. Should I update to the latest 1.0.3 version?

**Comment by jaanonim** [comment]
I don't have premium on ngrok so i don't have way to develop it. Also not everyone host on port 25565 (eg when you use single player lan option). If there is somebody that want's to develop that feel free to contribute.
